/**
 * Writes scripts/icons.mjs: the Lucide icons (ISC, lucide-static) the shop window's templates name,
 * as SVG markup, so the window carries them inline (they take the text colour, and Foundry needs
 * no network for them). Run after using a new icon in a template: `node tools/build-icons.mjs`.
 * tools/icons.test.mjs fails when a template names an icon the file lacks.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { iconsUsed } from "./icons-used.mjs";

const lucide = new URL("../node_modules/lucide-static/", import.meta.url);
const version = JSON.parse(readFileSync(new URL("package.json", lucide), "utf8")).version;

const names = [...iconsUsed()].sort();
const available = new Set(readdirSync(new URL("icons/", lucide)).map(f => f.replace(/\.svg$/, "")));
const missing = names.filter(n => !available.has(n));
if (missing.length) throw new Error(`not Lucide icons: ${missing.join(", ")}`);

// Only the shapes: the <svg> wrapper and its attributes are the helper's (scripts/icons.mjs `icon`).
// Cutting up to <svg> takes Lucide's license comment with it, its only comment (#196).
const inner = name => readFileSync(new URL(`icons/${name}.svg`, lucide), "utf8")
  .replace(/^[\s\S]*?<svg[^>]*>/, "").replace(/<\/svg>\s*$/, "")
  .replace(/\s*\n\s*/g, "").trim();

const body = names.map(n => `  ${JSON.stringify(n)}: ${JSON.stringify(inner(n))}`).join(",\n");
writeFileSync(new URL("../scripts/icons.mjs", import.meta.url), `/**
 * The shop window's icons (#145): Lucide ${version} (ISC, https://lucide.dev), only those the templates use.
 * Generated by tools/build-icons.mjs; don't edit by hand.
 */

export const ICONS = {
${body}
};

const ESCAPES = { "&": "&amp;", "\\"": "&quot;", "<": "&lt;", ">": "&gt;" };

/**
 * One icon as inline SVG, drawn in the current text colour, with \`attrs\` on the <svg> (values
 * escaped; names are the templates' own).
 *
 * @param {string} name  a key of ICONS
 * @param {Record<string, string>} [attrs]
 * @returns {string}
 */
export function icon(name, attrs = {}) {
  const shapes = ICONS[name];
  if (shapes === undefined) throw new Error(\`merchant-presets | no icon "\${name}"\`);
  const extra = Object.entries(attrs).map(([k, v]) => \` \${k}="\${String(v).replace(/[&"<>]/g, c => ESCAPES[c])}"\`).join("");
  return \`<svg class="mp-icon" data-icon="\${name}"\${extra} viewBox="0 0 24 24" fill="none" stroke="currentColor" \`
    + \`stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">\${shapes}</svg>\`;
}
`);
console.log(`scripts/icons.mjs: ${names.length} icons`);
